### ISSUE TITLE
running electron-packager doesn't work

### ISSUE THREAD

**Issue by johbra** [ahonn/shadow-electorn-starter#12]
Using a local installation of electron-packer:

npx electron-packager . HelloWorld

yields the the messages

Packaging app for platform darwin x64 using electron v15.3.1
ENOENT: no such file or directory, stat 'resources/public/.#index.html'

I have no idea where to look for the cause of the problem

Johannes

**Comment by kurtharriger** [comment]
You might give my updated template a try as it worked for me. 
https://github.com/kurtharriger/shadow-electron-starter

**Comment by ahonn** [comment]
resolved at https://github.com/ahonn/shadow-electron-starter/pull/13
